### ISSUE TITLE
dotnet version 8.0 error issue

### ISSUE THREAD

**Issue by Fvr9W** [Trellmor/jellyfin-mpc-shim#1]
## Issue Description

**Project Name:** jellyfin-mpc-shim

**Issue Type:** Bug Report

**Operating System:** Windows 11

**dotnet Version:** 8.0

**Error Screenshot:**![image](https://github.com/Trellmor/jellyfin-mpc-shim/assets/70867226/8635a0b5-eba5-4d2f-b8c2-f0d59ff9943c)

**Issue Description:**

After upgrading to dotnet version 8.0 on my Windows 11, the jellyfin-mpc-shim project is encountering an error as shown in the attached screenshot. This is causing the project to malfunction.

**Steps to Reproduce:**

1. Upgrade dotnet version to 8.0.
2. Run the jellyfin-mpc-shim project.

**Expected Behavior:**

After a successful dotnet upgrade, the jellyfin-mpc-shim project should run smoothly without encountering errors on my current Windows version.

**Additional Information:**

- Any troubleshooting steps you have attempted (if any).
- Any other relevant information that might be related to the issue.

**Comment by Trellmor** [comment]
Hi,

as far as I know you need to install the same .NET version the application was compiled for. That's .NET 7 for jellyfin-mpc-shim. Upgrading to .NET 8 should not remove the older .NET version, you should end up with both versions installed.

I'll update to .NET 8 for the next version, but that may take me a while. Meanwhile you should be able to install .NET 7.

**Comment by Trellmor** [comment]
jellyfin-mpc-shim [version 0.2.0](https://github.com/Trellmor/jellyfin-mpc-shim/releases/tag/v0.2.0) is now using .NET 8.
