### ISSUE TITLE
Unable to have two users use mpc-shim at the same time

### ISSUE THREAD

**Issue by ManGuyNY** [Trellmor/jellyfin-mpc-shim#6]
Basically what the title says. A buddy and I were trying to both do syncplay using this handy program, but it seems to only want to work for one of us at a time. Works fine if one of us uses the shim and the other uses the Jellyfin Media Player instead. We just can't both be using the shim.

I checked the Jellyfin Dashboard to diagnose, and it seems that whenever the other user starts the shim on their end, the first user is disconnected. They seem to overwrite each other. Closing the shim in the system tray also seems to close it for the other user as well. Is there a way to correct this behavior?

**Comment by Trellmor** [comment]
Thank you, every shim instance used the same device identifier leading to this problem. I've fixed it in [version 0.2.1](https://github.com/Trellmor/jellyfin-mpc-shim/releases/tag/v0.2.1)
